# Generated by Django 6.0.3 on 2026-03-25 16:00

import django.db.models.deletion
import functools
import news.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("title_uk", models.CharField(max_length=128, null=True)),
                ("title_en", models.CharField(max_length=128, null=True)),
                ("title_cnr", models.CharField(max_length=128, null=True)),
                ("title_hr", models.CharField(max_length=128, null=True)),
                ("title_bs", models.CharField(max_length=128, null=True)),
                ("title_it", models.CharField(max_length=128, null=True)),
                ("title_de", models.CharField(max_length=128, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("title_uk", models.CharField(max_length=128, null=True)),
                ("title_en", models.CharField(max_length=128, null=True)),
                ("title_cnr", models.CharField(max_length=128, null=True)),
                ("title_hr", models.CharField(max_length=128, null=True)),
                ("title_bs", models.CharField(max_length=128, null=True)),
                ("title_it", models.CharField(max_length=128, null=True)),
                ("title_de", models.CharField(max_length=128, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                (
                    "title_uk",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_cnr",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_hr",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_bs",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_it",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description_uk",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description_cnr",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description_hr",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description_bs",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description_it",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        help_text="Анонс для списку новин",
                        max_length=512,
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст статті")),
                (
                    "content_uk",
                    models.TextField(null=True, verbose_name="Текст статті"),
                ),
                (
                    "content_en",
                    models.TextField(null=True, verbose_name="Текст статті"),
                ),
                (
                    "content_cnr",
                    models.TextField(null=True, verbose_name="Текст статті"),
                ),
                (
                    "content_hr",
                    models.TextField(null=True, verbose_name="Текст статті"),
                ),
                (
                    "content_bs",
                    models.TextField(null=True, verbose_name="Текст статті"),
                ),
                (
                    "content_it",
                    models.TextField(null=True, verbose_name="Текст статті"),
                ),
                (
                    "content_de",
                    models.TextField(null=True, verbose_name="Текст статті"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Чернетка"),
                            ("published", "Опублікована"),
                            ("archived", "Архівована"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False,
                        help_text="Термінові новини надсилаються підписникам негайно",
                        verbose_name="Термінова",
                    ),
                ),
                (
                    "in_rotation",
                    models.BooleanField(
                        default=False,
                        help_text="Показувати в каруселі на головній",
                        verbose_name="В ротації",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="news.newstag",
                        verbose_name="Теги",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="news.topic",
                        verbose_name="Рубрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="Назва зображення"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=functools.partial(
                            news.models._upload_image, folder="article_gallery_images"
                        ),
                        verbose_name="Додаткове зображення",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleMainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="Назва зображення"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=functools.partial(
                            news.models._upload_image, folder="article_main_images"
                        ),
                        verbose_name="Головне зображення",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        to="news.article",
                    ),
                ),
            ],
        ),
    ]
