# Generated by Django 6.0.3 on 2026-03-26 15:45

import django.core.validators
import django.db.models.deletion
import functools
import menu.validators
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_digest_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstag',
            options={'ordering': ['title'], 'verbose_name': 'Тег новин', 'verbose_name_plural': 'Теги новин'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title'], 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AddField(
            model_name='newstag',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='description_bs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='description_cnr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='description_hr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='description_it',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_bs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_cnr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_hr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_it',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title_bs',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title_cnr',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title_hr',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title_it',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='title_uk',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_bs',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_cnr',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_de',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_hr',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_it',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_uk',
            field=models.CharField(max_length=128, null=True, verbose_name='Назва'),
        ),
        migrations.CreateModel(
            name='NewsTagLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=functools.partial(news.models._upload_image, folder='newstag_logos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), menu.validators.validate_svg_content], verbose_name='Логотип (SVG)')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='news.newstag')),
            ],
            options={
                'verbose_name': 'Логотип тега',
                'verbose_name_plural': 'Логотипи тегів',
            },
        ),
        migrations.CreateModel(
            name='TopicLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=functools.partial(news.models._upload_image, folder='topic_logos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), menu.validators.validate_svg_content], verbose_name='Логотип (SVG)')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='news.topic')),
            ],
            options={
                'verbose_name': 'Логотип рубрики',
                'verbose_name_plural': 'Логотипи рубрик',
            },
        ),
    ]
