# Generated by Django 6.0.3 on 2026-03-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_topic_newstag_description_and_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topiclogo',
            name='topic',
        ),
        migrations.AddField(
            model_name='article',
            name='primary_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_articles', to='news.newstag', verbose_name='Головний тег'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_articles', to='news.newstag', verbose_name='Додаткові теги'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopicLogo',
        ),
    ]
