# Generated by Django 6.0.3 on 2026-03-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0006_add_visitor_escalation"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ім'я відвідувача"
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("love", "❤️ Чудово"),
                            ("good", "😊 Добре"),
                            ("ok", "😐 Нормально"),
                            ("bad", "😕 Не дуже"),
                        ],
                        max_length=10,
                        verbose_name="Настрій",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Повідомлення"
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("language", models.CharField(blank=True, max_length=5)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="orders.order",
                        verbose_name="Замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
                "ordering": ["-created_at"],
            },
        ),
    ]
