# Generated by Django 6.0.3 on 2026-03-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0004_add_dish_availability"),
        ("orders", "0001_initial_order_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує"),
                            ("taken", "Готується"),
                            ("done", "Готово"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kitchen_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кухар",
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_ticket",
                        to="orders.orderitem",
                        verbose_name="Позиція замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тікет кухні",
                "verbose_name_plural": "Тікети кухні",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="KitchenAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_assignments",
                        to="menu.dish",
                        verbose_name="Страва",
                    ),
                ),
                (
                    "kitchen_user",
                    models.ForeignKey(
                        limit_choices_to={
                            "role__in": ["kitchen", "kitchen_supervisor"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кухар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розподіл кухні",
                "verbose_name_plural": "Розподіл кухні",
                "unique_together": {("dish", "kitchen_user")},
            },
        ),
    ]
