# Generated by Django 6.0.3 on 2026-03-15 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial_kitchen_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitchenticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["kitchen", "kitchen_supervisor"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kitchen_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кухар",
            ),
        ),
    ]
