# Generated by Django 6.0.3 on 2026-03-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_kitchenticket_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenticket",
            name="escalation_level",
            field=models.IntegerField(
                choices=[(0, "Немає"), (1, "Старший кухні"), (2, "Менеджер")],
                db_index=True,
                default=0,
            ),
        ),
    ]
