# Generated by Django 6.0.3 on 2026-03-16 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_add_escalation_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "target_waiter",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["waiter", "senior_waiter"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_handoffs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff",
                        to="kitchen.kitchenticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Передача страви",
                "verbose_name_plural": "Передачі страв",
            },
        ),
    ]
