# Generated by Django 6.0.3 on 2026-03-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_handoff_model"),
        ("orders", "0009_add_auto_skip_to_order_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitchenticket",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kitchen_tickets",
                to="orders.orderitem",
                verbose_name="Позиція замовлення",
            ),
        ),
    ]
