# Generated by Django 6.0.3 on 2026-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_ticket_per_portion"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenticket",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kitchenticket",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
