# Generated by Django 6.0.3 on 2026-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0006_add_ticket_delivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenticket",
            name="handed_off_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When cook handed dish to waiter (kitchen → waiter)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kitchenticket",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When waiter delivered dish to visitor (waiter → visitor)",
                null=True,
            ),
        ),
    ]
