# Generated by Django 6.0.3 on 2026-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationapproval",
            name="llm_accuracy",
            field=models.FloatField(
                blank=True, help_text="Meaning accuracy (0-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_average",
            field=models.FloatField(
                blank=True, help_text="Average of all scores", null=True
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_emotion",
            field=models.FloatField(
                blank=True, help_text="Emotion accuracy (0-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_ethics",
            field=models.FloatField(
                blank=True, help_text="Ethical appropriateness (0-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_grammar",
            field=models.FloatField(
                blank=True, help_text="Grammar correctness (0-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_quality",
            field=models.FloatField(
                blank=True, help_text="Translation quality (0-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_review_comment",
            field=models.TextField(
                blank=True, default="", help_text="Reviewer feedback / correction notes"
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_review_iterations",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of translate-review cycles"
            ),
        ),
        migrations.AddField(
            model_name="translationapproval",
            name="llm_style",
            field=models.FloatField(
                blank=True, help_text="Stylistic quality (0-10)", null=True
            ),
        ),
    ]
