# Generated by Django 6.0.1 on 2026-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="user_avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Менеджер"),
                    ("production", "Виробництво"),
                    ("finance", "Фінанси"),
                    ("waiter", "Офіціант"),
                    ("visitor", "Відвідувач"),
                ],
                default="visitor",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
