# Generated by Django 6.0.1 on 2026-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_add_avatar_and_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Електронна пошта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, unique=True, verbose_name="Ім'я користувача"
            ),
        ),
    ]
