# Generated by Django 6.0.3 on 2026-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_email_auth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Менеджер"),
                    ("kitchen_supervisor", "Старший кухні"),
                    ("kitchen", "Виробництво"),
                    ("senior_waiter", "Старший офіціант"),
                    ("waiter", "Офіціант"),
                    ("visitor", "Відвідувач"),
                ],
                default="visitor",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
