# Generated by Django 6.0.3 on 2026-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_migrate_legacy_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_title",
            field=models.CharField(
                blank=True,
                help_text="Наприклад: Повариха, Бармен, Майстер десертів",
                max_length=60,
                verbose_name="Посада для відвідувачів",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="public_name",
            field=models.CharField(
                blank=True,
                help_text="Ім'я без прізвища для відвідувачів",
                max_length=50,
                verbose_name="Публічне ім'я",
            ),
        ),
    ]
