# Generated by Django 6.0.3 on 2026-03-25 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_add_staff_display_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")],
                        max_length=20,
                        verbose_name="Тип каналу",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Email, Telegram chat ID, або номер телефону",
                        max_length=255,
                        verbose_name="Адреса",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Верифіковано"),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Менше число — вищий пріоритет",
                        verbose_name="Пріоритет",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал комунікації",
                "verbose_name_plural": "Канали комунікації",
                "ordering": ["priority"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "channel_type"), name="unique_channel_per_type"
                    )
                ],
            },
        ),
    ]
