# Generated by Django 6.0.3 on 2026-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_add_communication_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("telegram", "Telegram"),
                ],
                default="email",
                max_length=20,
                verbose_name="Джерело реєстрації",
            ),
        ),
    ]
