# Generated by Django 6.0.3 on 2026-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_add_registration_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Менеджер"),
                    ("kitchen_supervisor", "Старший кухні"),
                    ("kitchen", "Виробництво"),
                    ("senior_waiter", "Старший офіціант"),
                    ("waiter", "Офіціант"),
                    ("editor", "Редактор"),
                    ("corrector", "Коректор"),
                    ("visitor", "Відвідувач"),
                ],
                default="visitor",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
