# Generated by Django 6.0.3 on 2026-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_add_editor_corrector_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="corrector_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Коди мов для коректури: en, cnr, hr, bs, it, de",
                verbose_name="Мови коректора",
            ),
        ),
    ]
