# Generated by Django 6.0.1 on 2026-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["number_in_line", "title"]},
        ),
        migrations.AddField(
            model_name="category",
            name="number_in_line",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Менше число — вище у списку",
                verbose_name="Порядок у меню",
            ),
        ),
    ]
