# Generated by Django 6.0.3 on 2026-03-15 08:21

import django.core.validators
import functools
import menu.models
import menu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_populate_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="availability",
            field=models.CharField(
                choices=[
                    ("available", "В наявності"),
                    ("low", "Закінчується — уточнюйте у офіціанта"),
                    ("out", "Немає"),
                ],
                db_index=True,
                default="available",
                max_length=16,
                verbose_name="Наявність",
            ),
        ),
        migrations.AlterField(
            model_name="categorylogo",
            name="image",
            field=models.FileField(
                help_text="Only upload .svg files, which allow for high-quality scaling without loss of clarity.",
                upload_to=functools.partial(
                    menu.models.upload_image, folder="category_logos"
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    ),
                    menu.validators.validate_svg_content,
                ],
                verbose_name="Vector logo (SVG)",
            ),
        ),
        migrations.AlterField(
            model_name="taglogo",
            name="image",
            field=models.FileField(
                help_text="Only upload .svg files, which allow for high-quality scaling without loss of clarity.",
                upload_to=functools.partial(
                    menu.models.upload_image, folder="tag_logos"
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    ),
                    menu.validators.validate_svg_content,
                ],
                verbose_name="Vector logo (SVG)",
            ),
        ),
    ]
