# Generated by Django 6.0.3 on 2026-03-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_add_dish_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_de",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_sr",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_uk",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_sr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_uk",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_de",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_en",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_sr",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_uk",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title_sr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title_uk",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_de",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_en",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_sr",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_uk",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_de",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_sr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_uk",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
