# Generated by Django 6.0.3 on 2026-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_add_translation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("title_uk", models.CharField(max_length=128, null=True)),
                ("title_en", models.CharField(max_length=128, null=True)),
                ("title_sr", models.CharField(max_length=128, null=True)),
                ("title_de", models.CharField(max_length=128, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji icon: 🌾 🥛 🥜", max_length=10
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dish",
            name="allergens",
            field=models.ManyToManyField(
                blank=True,
                related_name="dishes",
                to="menu.allergen",
                verbose_name="Алергени",
            ),
        ),
    ]
