# Generated by Django 6.0.3 on 2026-03-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_add_allergen_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergen",
            name="title_bs",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="allergen",
            name="title_hr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="allergen",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_bs",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_hr",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="description_it",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_bs",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_hr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_bs",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_hr",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="description_it",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title_bs",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title_hr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_bs",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_hr",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_it",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_bs",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_hr",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_it",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
