# Generated by Django 6.0.3 on 2026-03-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_add_hr_bs_it_translation_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allergen",
            old_name="title_sr",
            new_name="title_cnr",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="description_sr",
            new_name="description_cnr",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="title_sr",
            new_name="title_cnr",
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="description_sr",
            new_name="description_cnr",
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="title_sr",
            new_name="title_cnr",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="description_sr",
            new_name="description_cnr",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="title_sr",
            new_name="title_cnr",
        ),
    ]
