# Generated by Django 6.0.3 on 2026-03-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial_order_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_escalation_level",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("not_set", "Не визначено"),
                    ("cash", "Готівка"),
                    ("online", "Онлайн"),
                ],
                default="not_set",
                max_length=10,
            ),
        ),
    ]
