# Generated by Django 6.0.3 on 2026-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_add_payment_method_and_escalation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("not_set", "Не визначено"),
                    ("cash", "Готівка"),
                    ("online", "Онлайн"),
                ],
                default="not_set",
                max_length=20,
            ),
        ),
    ]
