# Generated by Django 6.0.3 on 2026-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_increase_payment_method_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location_hint",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Де вас знайти (необов'язково)"
            ),
        ),
    ]
