# Generated by Django 6.0.3 on 2026-03-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_access_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("slow", "Довго чекаю"),
                            ("wrong", "Щось не те"),
                            ("question", "Маю питання"),
                            ("other", "Інше"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Коментар"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Офіціант"),
                            (2, "Старший офіціант"),
                            (3, "Менеджер"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Відкрита"),
                            ("acknowledged", "Побачено"),
                            ("resolved", "Вирішено"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, max_length=300)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="orders.order",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
