# Generated by Django 6.0.3 on 2026-03-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_add_order_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Чернетка"),
                    ("submitted", "Створено"),
                    ("accepted", "Прийнято"),
                    ("verified", "Верифіковано"),
                    ("in_progress", "Готується"),
                    ("ready", "Готово"),
                    ("delivered", "Доставлено"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
