# Generated by Django 6.0.3 on 2026-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_split_approved_to_accepted_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderevent",
            name="is_auto_skip",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when this event was generated by auto-skipping a flow step",
            ),
        ),
    ]
