# Generated by Django 6.0.3 on 2026-03-19 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0007_add_handed_off_at"),
        ("orders", "0010_add_actor_to_orderevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StepEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("submit_accept", "Прийняття замовлення"),
                            ("accept_verify", "Верифікація"),
                            ("pending_taken", "Взяття тікета кухарем"),
                            ("taken_done", "Приготування"),
                            ("done_handoff", "Передача офіціанту"),
                            ("deliver_pay", "Оплата"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(choices=[(1, "Старший"), (2, "Менеджер")]),
                ),
                (
                    "owner_role",
                    models.CharField(
                        blank=True,
                        help_text="Pool blame role, e.g. 'senior_waiter', 'kitchen_supervisor'",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "caused_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_escalations_caused",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_escalations",
                        to="orders.order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_escalations_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_escalations",
                        to="kitchen.kitchenticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["step", "level", "resolved_at"],
                        name="orders_step_step_4442ab_idx",
                    )
                ],
            },
        ),
    ]
