# Generated by Django 6.0.3 on 2026-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_add_accepted_at_and_step_escalation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Чернетка"),
                    ("submitted", "Створено"),
                    ("accepted", "Прийнято"),
                    ("verified", "Верифіковано"),
                    ("in_progress", "Готується"),
                    ("ready", "Готово"),
                    ("delivered", "Доставлено"),
                    ("cancelled", "Скасовано"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
