# Generated by Django 6.0.3 on 2026-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_add_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderevent',
            name='message_key',
            field=models.CharField(blank=True, help_text='Gettext message key for i18n (English template with %(name)s params)', max_length=300),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='msg_class',
            field=models.CharField(blank=True, help_text='CSS class for terminal log styling', max_length=30),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic params for message_key interpolation'),
        ),
    ]
